# Generated by Django 4.2.7 on 2025-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_subcategory_column_lg_alter_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='services/'),
            preserve_default=False,
        ),
    ]
