# Generated by Django 4.2.7 on 2025-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_created_at_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
