# Generated by Django 4.2.7 on 2025-01-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_instructor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='twitter_url',
        ),
    ]
