# Generated by Django 4.2.7 on 2025-01-20 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_curriculum_course_video_url_testimonial_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 20, 13, 35, 14, 376943, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
